export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'

export const SORT_PRODUCTS = 'SORT_PRODUCTS'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const FILTER_PRODUCTS_BY_GENDER = 'FILTER_PRODUCTS_BY_GENDER'
export const SORT_PRODUCTS_CHANGE = 'SORT_PRODUCTS_CHANGE'