export const CATEGORIES = [
  {name: 'Blouses and shirts', count: 743},
  {name: 'Bodysuit', count: 743},
  {name: 'Costumes', count: 743},
  {name: 'Pants', count: 743},
  {name: 'Outerwear', count: 743},
  {name: 'Jumpers & Sweaters', count: 743},
  {name: 'Jeans', count: 743},
  {name: 'Home clothes', count: 743},
  {name: 'Jumpsuits', count: 743},
  {name: 'Beachwear', count: 743},
  {name: 'Shorts', count: 743},
  {name: 'Skirts', count: 743},
  {name: 'Tops', count: 743},
  {name: 'Socks, stockings, tights', count: 743},
]